package com.yuanqi.domain.commdity;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Table(name = "commodity")
@Entity
public class Commodity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CommodityId
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CommodityName
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.Type
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CommodityPrice
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    private BigDecimal commodityPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CommodityNumber
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    private Long commodityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CreateTime
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.LastUpdateTime
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CommodityId
     *
     * @return the value of commodity.CommodityId
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public Long getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CommodityId
     *
     * @param commodityId the value for commodity.CommodityId
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public void setCommodityId(Long commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CommodityName
     *
     * @return the value of commodity.CommodityName
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CommodityName
     *
     * @param commodityName the value for commodity.CommodityName
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.Type
     *
     * @return the value of commodity.Type
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.Type
     *
     * @param type the value for commodity.Type
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CommodityPrice
     *
     * @return the value of commodity.CommodityPrice
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public BigDecimal getCommodityPrice() {
        return commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CommodityPrice
     *
     * @param commodityPrice the value for commodity.CommodityPrice
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public void setCommodityPrice(BigDecimal commodityPrice) {
        this.commodityPrice = commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CommodityNumber
     *
     * @return the value of commodity.CommodityNumber
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public Long getCommodityNumber() {
        return commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CommodityNumber
     *
     * @param commodityNumber the value for commodity.CommodityNumber
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public void setCommodityNumber(Long commodityNumber) {
        this.commodityNumber = commodityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CreateTime
     *
     * @return the value of commodity.CreateTime
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CreateTime
     *
     * @param createTime the value for commodity.CreateTime
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.LastUpdateTime
     *
     * @return the value of commodity.LastUpdateTime
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.LastUpdateTime
     *
     * @param lastUpdateTime the value for commodity.LastUpdateTime
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Fri May 10 15:35:40 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commodityId=").append(commodityId);
        sb.append(", commodityName=").append(commodityName);
        sb.append(", type=").append(type);
        sb.append(", commodityPrice=").append(commodityPrice);
        sb.append(", commodityNumber=").append(commodityNumber);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}