server:
  port: 3001


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1/fristdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: yuantu123
  #  spring.datasource.driver-class-name=net.sf.log4jdbc.DriverSpy
  #  spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql=true: